/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated.stats'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated.me'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated.matches.index'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated.players.$playerId'
import { Route as AuthenticatedMatchesNewRouteImport } from './routes/_authenticated.matches.new'
import { Route as AuthenticatedMatchesMatchIdEditRouteImport } from './routes/_authenticated.matches.$matchId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatchesNewRoute = AuthenticatedMatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatchesMatchIdEditRoute =
  AuthenticatedMatchesMatchIdEditRouteImport.update({
    id: '/matches/$matchId/edit',
    path: '/matches/$matchId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/me': typeof AuthenticatedMeRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/matches/new': typeof AuthenticatedMatchesNewRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
  '/matches/$matchId/edit': typeof AuthenticatedMatchesMatchIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/me': typeof AuthenticatedMeRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/': typeof AuthenticatedIndexRoute
  '/matches/new': typeof AuthenticatedMatchesNewRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/matches/$matchId/edit': typeof AuthenticatedMatchesMatchIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/matches/new': typeof AuthenticatedMatchesNewRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/_authenticated/matches/$matchId/edit': typeof AuthenticatedMatchesMatchIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/me'
    | '/stats'
    | '/matches/new'
    | '/players/$playerId'
    | '/matches/'
    | '/matches/$matchId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/me'
    | '/stats'
    | '/'
    | '/matches/new'
    | '/players/$playerId'
    | '/matches'
    | '/matches/$matchId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/me'
    | '/_authenticated/stats'
    | '/_authenticated/'
    | '/_authenticated/matches/new'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/matches/'
    | '/_authenticated/matches/$matchId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches/new': {
      id: '/_authenticated/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof AuthenticatedMatchesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches/$matchId/edit': {
      id: '/_authenticated/matches/$matchId/edit'
      path: '/matches/$matchId/edit'
      fullPath: '/matches/$matchId/edit'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMatchesNewRoute: typeof AuthenticatedMatchesNewRoute
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
  AuthenticatedMatchesMatchIdEditRoute: typeof AuthenticatedMatchesMatchIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMatchesNewRoute: AuthenticatedMatchesNewRoute,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
  AuthenticatedMatchesMatchIdEditRoute: AuthenticatedMatchesMatchIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
